#!/usr/bin/env python3
"""Export a verified PyTorch candidate as a self-checking ONNX bundle."""
from __future__ import annotations
import argparse,json,platform
from pathlib import Path
import numpy as np,onnx,onnxruntime as ort,torch
from ml.evaluation.evaluate import calculate,held_out,ranked
from ml.training.train import ManifestDataset,build_model,read,sha256,state_hash

def main()->int:
 p=argparse.ArgumentParser();p.add_argument("--checkpoint",type=Path,required=True);p.add_argument("--run-metadata",type=Path,required=True);p.add_argument("--evaluation",type=Path,required=True);p.add_argument("--catalog",type=Path,default=Path("ml/catalog/mvp-car-catalog.json"));p.add_argument("--configs",type=Path,default=Path("ml/training/baselines.json"));p.add_argument("--manifest",type=Path,required=True);p.add_argument("--splits",type=Path,required=True);p.add_argument("--root",type=Path,required=True);p.add_argument("--output",type=Path,required=True);p.add_argument("--opset",type=int,default=18);p.add_argument("--atol",type=float,default=1e-5);p.add_argument("--rtol",type=float,default=1e-4);a=p.parse_args()
 run,evaluation,catalog,configs=read(a.run_metadata),read(a.evaluation),read(a.catalog),read(a.configs);checkpoint=torch.load(a.checkpoint,map_location="cpu",weights_only=False);identity=run["identity"]
 if checkpoint.get("identity")!=identity or evaluation["identities"]["checkpoint_state_sha256"]!=run["checkpoint_state_sha256"]:raise ValueError("checkpoint/evaluation identity mismatch")
 if identity["manifest_sha256"]!=sha256(a.manifest) or identity["splits_sha256"]!=sha256(a.splits) or run["catalog_sha256"]!=sha256(a.catalog) or run["config_sha256"]!=sha256(a.configs):raise ValueError("input identity mismatch")
 classes=catalog["classes"];class_ids=[x["class_id"] for x in classes];config=configs["baselines"][identity["baseline"]];model=build_model(config,len(classes));model.load_state_dict(checkpoint["model"]);model.eval()
 if state_hash(model)!=run["checkpoint_state_sha256"]:raise ValueError("checkpoint tensor hash mismatch")
 a.output.mkdir(parents=True,exist_ok=True);model_path=a.output/"model.onnx";sample=torch.zeros(1,3,config["input_size"],config["input_size"],dtype=torch.float32);program=torch.onnx.export(model,(sample,),input_names=["images"],output_names=["logits"],opset_version=a.opset,dynamo=True,external_data=False);program.save(model_path,external_data=False)
 session=ort.InferenceSession(str(model_path),providers=["CPUExecutionProvider"]);input_meta=session.get_inputs()[0];output_meta=session.get_outputs()[0]
 if input_meta.name!="images" or input_meta.shape!=[1,3,config["input_size"],config["input_size"]] or output_meta.name!="logits" or output_meta.shape!=[1,len(classes)]:raise ValueError("ONNX input/output contract mismatch")
 manifest_data=read(a.manifest);split_data=read(a.splits);rows=held_out(manifest_data,split_data,a.root);dataset=ManifestDataset(rows,a.root,{x:i for i,x in enumerate(class_ids)},config);records_t=[];records_o=[];max_abs=max_rel=0.0;ranking_equal=True
 with torch.no_grad():
  for i in range(len(dataset)):
   image,target=dataset[i];batch=image.unsqueeze(0);pt=model(batch).numpy();actual=session.run(["logits"],{"images":batch.numpy()})[0];delta=np.abs(pt-actual);max_abs=max(max_abs,float(delta.max()));max_rel=max(max_rel,float((delta/np.maximum(np.abs(pt),1e-12)).max()));ranking_equal=ranking_equal and ranked(pt[0].tolist())==ranked(actual[0].tolist());records_t.append({"asset_id":rows[i]["asset_id"],"target_index":target,"logits":pt[0].tolist()});records_o.append({"asset_id":rows[i]["asset_id"],"target_index":target,"logits":actual[0].tolist()})
 if not np.allclose([x["logits"] for x in records_t],[x["logits"] for x in records_o],atol=a.atol,rtol=a.rtol) or not ranking_equal:raise ValueError("PyTorch/ONNX numeric or ranking equivalence failed")
 pt_metrics=calculate(records_t,class_ids,evaluation["thresholds"]["minimum_per_class_support"]);onnx_metrics=calculate(records_o,class_ids,evaluation["thresholds"]["minimum_per_class_support"])
 for key in ("top_one_accuracy","top_five_accuracy","macro_top_one_accuracy","macro_top_five_accuracy"):
  if abs(pt_metrics["aggregate"][key]-onnx_metrics["aggregate"][key])>1e-12:raise ValueError("held-out metric equivalence failed")
 class_map={"schema_version":"1.0.0","catalog_id":catalog["catalog_id"],"class_count":len(classes),"classes":[{"index":i,**x} for i,x in enumerate(classes)]};class_path=a.output/"class-map.json";class_path.write_text(json.dumps(class_map,indent=2,sort_keys=True)+"\n");notice=a.output/"NOTICE.candidate.txt"
 if config["weight_source"]=="random_initialization":sources=[{"name":"TorchVision MobileNetV3 architecture","source_url":"https://github.com/pytorch/vision","license":"BSD-3-Clause","license_url":"https://github.com/pytorch/vision/blob/main/LICENSE"}];notice.write_text("Experimental random-initialized candidate; not approved for distribution. Architecture code: TorchVision BSD-3-Clause.\n")
 else:sources=[{"name":"timm MobileNetV3 Small pretrained artifact","source_url":"https://huggingface.co/timm/mobilenetv3_small_100.lamb_in1k/tree/1824797e7887cbec1990e4adbd6675960a36c589","license":"Apache-2.0","license_url":"https://www.apache.org/licenses/LICENSE-2.0","sha256":config["weight_sha256"],"training_provenance":"ImageNet-1K"}];notice.write_text("Experimental fine-tuned candidate; not approved for distribution. Source artifact: timm/mobilenetv3_small_100.lamb_in1k, Apache-2.0, trained on ImageNet-1K.\n")
 manifest={"schema_version":"1.0.0","bundle_id":"categorizer-candidate-"+run["checkpoint_state_sha256"][:12],"model_version":"0.1.0","artifact_status":"release_candidate","model":{"filename":"model.onnx","format":"ONNX","sha256":sha256(model_path),"size_bytes":model_path.stat().st_size},"class_map":{"filename":"class-map.json","schema_version":"1.0.0","catalog_id":catalog["catalog_id"],"class_count":len(classes),"sha256":sha256(class_path)},"input":{"tensor_name":"images","element_type":"float32","layout":"NCHW","shape":[1,3,config["input_size"],config["input_size"]],"color_order":"RGB"},"preprocessing":run["preprocessing"],"output":{"tensor_name":"logits","element_type":"float32","shape":[1,len(classes)],"class_axis":1,"semantics":"logits","score_transform":"softmax","ranking":"descending_score_then_ascending_class_index","top_k":min(5,len(classes))},"onnx_runtime":{"opset":a.opset,"minimum_version":"1.27.0","required_execution_providers":["CPUExecutionProvider"]},"licenses":{"model_spdx_expression":"LicenseRef-Categorizer-Candidate-NotForDistribution","notice_files":[notice.name],"source_artifacts":sources}};(a.output/"model-manifest.json").write_text(json.dumps(manifest,indent=2,sort_keys=True)+"\n")
 graph=onnx.load(model_path);operators=sorted({(node.domain or "ai.onnx",node.op_type) for node in graph.graph.node});report={"schema_version":"1.0.0","tolerances":{"atol":a.atol,"rtol":a.rtol},"numeric":{"max_abs_difference":max_abs,"max_relative_difference":max_rel},"rankings_equal":ranking_equal,"held_out":{"pytorch":pt_metrics["aggregate"],"onnxruntime":onnx_metrics["aggregate"]},"compatibility":{"onnx_checker":"passed","runtime_version":ort.__version__,"providers":session.get_providers(),"opset":a.opset,"operators":[{"domain":d,"type":o} for d,o in operators]},"identities":{"model_sha256":sha256(model_path),"class_map_sha256":sha256(class_path),"checkpoint_state_sha256":state_hash(model)},"runtime":{"python":platform.python_version(),"torch":torch.__version__}};onnx.checker.check_model(graph);(a.output/"equivalence-report.json").write_text(json.dumps(report,indent=2,sort_keys=True)+"\n");print(f"RESULT OK model_sha256={manifest['model']['sha256']} max_abs={max_abs:.8g} rankings_equal={ranking_equal} held_out_top5={onnx_metrics['aggregate']['top_five_accuracy']:.6f}");return 0
if __name__=="__main__":raise SystemExit(main())
